---
title: "Literature on the Wild Bootstrap and Clustered Inference in Regression Models"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Literature on the Wild Bootstrap and Clustered Inference in Regression Models}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Academic Papers

+ [Roodman, MacKinnon, Nielsen & Webb - Fast and Wild Bootstrap Inference (Stata Journal), 2019](https://journals.sagepub.com/doi/pdf/10.1177/1536867X19830877). The paper to read if you think that the performance of `fwildclusterboot` resembles black magic. Introduces `boottest` - the Stata software package `fwildclusterboot` is modeled after - and contains a great introduction to (almost) all features of the wild cluster bootstrap implemented in `fwildclusterboot`. 

+ [MacKinnon, Nielsen & Webb - Fast and Reliable Jackknife and Bootstrap
Methods for Cluster-Robust Inference (Journal of Applied Econometrics), 2023](https://arxiv.org/pdf/2301.04527.pdf) Introduces the "31", "33", "13" bootstrap types, explains how to compute them quickly, and contrasts their empirical performance in Monte Carlo studies. Argues in favour of the "31" method. 

+ [MacKinnon - Fast cluster bootstrap methods for linear regression models (Econometrics and Statistics, 2021)](https://www.econstor.eu/bitstream/10419/247206/1/qed-wp-1465.pdf) Discusses computational tricks for speeding up wild cluster bootstrap inference. Further provides a nice discussion of (bootstrap) test inversion to compute confidence intervals. 

+ [MacKinnon, Nielsen & Webb - Cluster-robust inference: A guide to empirical practice (Journal of Econometrics), 2023](https://www.sciencedirect.com/science/article/pii/S0304407622000781) Broad introduction and state-of-the-art literature survey of concepts around clustered errors.

+ [Webb - Reworking wild bootstrap based inference for clustered errors (forthcoming at Canadian Journal of Economics)](https://ideas.repec.org/p/qed/wpaper/1315.html) Introduces "Webb" weights, which are the recommended wild bootstrap weight type when the number of clusters are very small. 

+ [MacKinnon & Webb -  The wild bootstrap for few (treated) clusters (Econometrics Journal), 2018](https://academic.oup.com/ectj/article-abstract/21/2/114/5078969) Introduces the subcluster bootstrap for regressions with few treated clusters (e.g. difference-in-differences regressions with one treated cluster).

+ [MacKinnon - Wild Cluster Bootstrap Confidence Intervals (L'Actualité économique), 2015](https://www.erudit.org/en/journals/ae/1900-v1-n1-ae02507/1036912ar.pdf) Discusses how to invert a bootstrap to obtain a confidence interval.

+ [Davidson & MacKinnon - Wild bootstrap tests for IV regression (Journal of Economic and Business Statistics), 2010](https://www.tandfonline.com/doi/abs/10.1198/jbes.2009.07221) Introduces the WRE bootstrap / wild cluster bootstrap for instrumental variables regression.

+ [Cameron, Gelbach & Miller - Bootstrap-based improvements for inference with clustered errors (Review of Economics and Statistics)](https://www.econstor.eu/bitstream/10419/31404/1/514886757.pdf) The paper that started the literature on wild cluster bootstrap inference. Simulation evidence that the wild cluster bootstrap works remarkably well when there are only few clusters. 

+ [Flachaire - Bootstrapping heteroskedastic regression models: wild bootstrap vs. pairs bootstrap (Computational Statistics & Data Analysis), 2005](https://shs.hal.science/file/index/docid/175910/filename/Flachaire_03a.pdf) Provides simulation evidence of the performance of *heteroskedastic* wild bootstrap procedures. 

+ [MacKinnon - Thirty Years of Heteroskedasticity-Robust Inference, 2012](https://www.econ.queensu.ca/sites/econ.queensu.ca/files/qed_wp_1268.pdf) More simulation evidence on the performance of the HC1-HC3 vcov estimators vs the wild bootstrap.

+ [Joshi, Megha, James E. Pustejovsky, and S. Natasha Beretvas - "Cluster wild bootstrapping to handle dependent effect sizes in meta‐analysis with a small number of studies." (Research Synthesis Methods), 2022](https://onlinelibrary.wiley.com/doi/abs/10.1002/jrsm.1554) Nice simulations on the empirical performance of the wild cluster bootstrap for tests of multiple joint hypotheses. 
 
+ [Kline & Santos - A Score Based Approach to Wild Bootstrap Inference (Journal of Econometric Methods), 2012](https://eml.berkeley.edu/~pkline/papers/ScoreFinal_web.pdf) Introduces a score based wild bootstrap for non-linear regression models. 

## Links, blogposts, etc

[Stata blog - Heteroskedasticity robust standard errors: Some practical considerations](https://blog.stata.com/2022/10/06/heteroskedasticity-robust-standard-errors-some-practical-considerations/) Extensive simulations on small sample properties of HC estimators, inlcuding the wild bootstrap


