# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Matrix Multiplication via Eigen
#' @param A A matrix. 
#' @param B A matrix.
#' @param nthreads Integer. Number of threads to use for matrix multiplication.
#' @return A matrix
eigenMatMult <- function(A, B, nthreads) {
    .Call('_fwildclusterboot_eigenMatMult', PACKAGE = 'fwildclusterboot', A, B, nthreads)
}

#' Matrix Multiplication via Eigen
#' @param A A matrix. 
#' @param B A matrix.
#' @param nthreads Integer. Number of threads to use for matrix multiplication.
#' @return A matrix
eigenMapMatMult <- function(A, B, nthreads) {
    .Call('_fwildclusterboot_eigenMapMatMult', PACKAGE = 'fwildclusterboot', A, B, nthreads)
}

#' Get maximum number of threads on hardware for open mp support
#' @return The maximum number of threads supported.
cpp_get_nb_threads <- function() {
    .Call('_fwildclusterboot_cpp_get_nb_threads', PACKAGE = 'fwildclusterboot')
}

