# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Matrix Multiplication via Eigen
#' @param A A matrix. 
#' @param B A matrix.
#' @return A matrix
eigenMatMult <- function(A, B) {
    .Call('_fwildclusterboot_eigenMatMult', PACKAGE = 'fwildclusterboot', A, B)
}

