# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eigenMatMult <- function(A, B) {
    .Call('_fwildclusterboot_eigenMatMult', PACKAGE = 'fwildclusterboot', A, B)
}

Rcpp_matrix_List_sum <- function(x) {
    .Call('_fwildclusterboot_Rcpp_matrix_List_sum', PACKAGE = 'fwildclusterboot', x)
}

naomit_cpp <- function(x) {
    .Call('_fwildclusterboot_naomit_cpp', PACKAGE = 'fwildclusterboot', x)
}

